In [28]:
import pandas as pd
# loading dataframe
df = pd.read_csv("../data/Sales_transactions_2022_2025.csv")
# printing first ten rows
df.head(10)

,Transaction_ID,Order_ID,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Customer_Segment,Order_Date,Order_Time,Sales_Channel,...,Order_Status,Shipping_Method,Delivery_Days,Return_Flag,Return_Reason,Sales_Representative,Promotion_Code,Customer_Rating,Inventory_Level,Order_Year
0,T02016694,O0116694,C01482,Sophia Smith,28.0,Male,Consumer,2022-10-06,11:30:55,Online,...,Completed,Standard,4.0,No,NaN,James Anderson,SAVE10,4.0,81.0,2022
1,T02016374,O0108187,C01591,Hannah King,46.0,Female,Consumer,2024-06-03,17:06:29,Online,...,Completed,Standard,6.0,No,NaN,Ella Lewis,NaN,5.0,123.0,2024
2,T02004099,O0104099,C04140,Emma Wilson,42.0,Male,Consumer,2024-12-19,08:22:11,Online,...,Shipped,Standard,4.0,No,NaN,Liam Davis,NaN,4.0,93.0,2024
3,T02010280,O0110280,C03663,Daniel Clark,18.0,Male,Corporate,2025-10-05,14:32:43,B2B Portal,...,Completed,Next Day,2.0,No,NaN,Grace Harris,HOLIDAY20,NaN,59.0,2025
4,T02012685,O0112685,C02749,Sophia Smith,37.0,Male,Returning Customer,2022-09-13,14:55:16,B2B Portal,...,Completed,Express,2.0,No,NaN,Sophia Brown,NaN,2.0,56.0,2022
5,T02003704,O0101852,C00959,Mia Miller,42.0,Non-binary,Corporate,2023-03-27,10:40:05,Retail Store,...,Completed,Pickup,0.0,No,NaN,Noah Wilson,SAVE10,1.0,35.0,2023
6,T02016542,O0116542,C02232,Evelyn Adams,46.0,Female,New Customer,2022-07-25,14:32:42,Online,...,Completed,Pickup,0.0,No,NaN,Ella Lewis,NaN,2.0,67.0,2022
7,T02013460,O0113460,C00719,Olivia Walker,44.0,Female,Consumer,2024-02-20,03:57:57,Online,...,Returned,Express,2.0,Yes,Damaged,Ella Lewis,NaN,5.0,59.0,2024
8,T02001029,O0101029,C01511,Emily Moore,54.0,Female,Consumer,2024-12-25,11:38:30,Online,...,Completed,Standard,7.0,No,NaN,Ella Lewis,NaN,NaN,57.0,2024
9,T02001635,O0101635,C04415,Freya Williams,49.0,Female,Consumer,2022-01-18,08:37:21,B2B Portal,...,Returned,Standard,7.0,Yes,Changed Mind,Olivia Martin,NaN,5.0,NaN,2022

In [29]:
# Show information on each column
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18045 entries, 0 to 18044
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Transaction_ID        18045 non-null  str
 1   Order_ID              18045 non-null  str
 2   Customer_ID           18045 non-null  str
 3   Customer_Name         17937 non-null  str
 4   Customer_Age          17827 non-null  float64
 5   Customer_Gender       17883 non-null  str
 6   Customer_Segment      18045 non-null  str
 7   Order_Date            18045 non-null  str
 8   Order_Time            18045 non-null  str
 9   Sales_Channel         18045 non-null  str
 10  Store_ID              18045 non-null  str
 11  Store_Name            18045 non-null  str
 12  Country               18045 non-null  str
 13  Region                18045 non-null  str
 14  City                  18045 non-null  str
 15  Product_ID            18045 non-null  str
 16  Product_Name          17901 non-null  str
 17  Product_Category      18045 non-null  str
 18  Product_Subcategory   18045 non-null  str
 19  Quantity              18045 non-null  int64
 20  Unit_Price            18045 non-null  float64
 21  Discount_Percentage   18045 non-null  float64
 22  Sales_Amount          18045 non-null  float64
 23  Cost_Amount           18045 non-null  float64
 24  Profit                18045 non-null  float64
 25  Payment_Method        17898 non-null  str
 26  Order_Status          18045 non-null  str
 27  Shipping_Method       18045 non-null  str
 28  Delivery_Days         17883 non-null  float64
 29  Return_Flag           18045 non-null  str
 30  Return_Reason         1877 non-null   str
 31  Sales_Representative  18045 non-null  str
 32  Promotion_Code        8308 non-null   str
 33  Customer_Rating       14610 non-null  float64
 34  Inventory_Level       17847 non-null  float64
 35  Order_Year            18045 non-null  int64
dtypes: float64(9), int64(2), str(25)
memory usage: 5.0 MB

In [30]:
# Statistical information on numerical columns
df.describe()

,Customer_Age,Quantity,Unit_Price,Discount_Percentage,Sales_Amount,Cost_Amount,Profit,Delivery_Days,Customer_Rating,Inventory_Level,Order_Year
count,17827.000000,18045.000000,18045.000000,18045.000000,18045.000000,18045.000000,18045.000000,17883.000000,14610.000000,17847.000000,18045.000000
mean,38.916924,2.127127,232.685633,6.256858,457.309027,366.001156,91.404131,2.262204,3.985969,70.257914,2023.566417
std,10.727357,1.786212,294.208022,6.881178,856.597181,705.866738,167.827883,2.321656,1.008422,22.042609,1.118744
min,4.000000,-3.000000,21.390000,0.000000,16.680000,12.170000,-299.310000,0.000000,1.000000,0.000000,2022.000000
25%,32.000000,1.000000,53.380000,0.000000,78.530000,56.120000,19.480000,0.000000,4.000000,55.000000,2023.000000
50%,39.000000,2.000000,99.870000,5.000000,168.810000,122.300000,40.190000,1.000000,4.000000,70.000000,2024.000000
75%,46.000000,3.000000,285.580000,10.000000,472.450000,376.020000,93.270000,4.000000,5.000000,85.000000,2025.000000
max,112.000000,11.000000,1425.090000,110.000000,14303.070000,10791.000000,3512.080000,10.000000,5.000000,157.000000,2025.000000

In [31]:
# Missing value count
for column in df.columns:
    nullCount = df[column].isna().sum()
    nullPercent = round(nullCount/len(df)*100, 3)
    print(f"{column}: {nullCount} missing ({nullPercent}%)")

Transaction_ID: 0 missing (0.0%)
Order_ID: 0 missing (0.0%)
Customer_ID: 0 missing (0.0%)
Customer_Name: 108 missing (0.599%)
Customer_Age: 218 missing (1.208%)
Customer_Gender: 162 missing (0.898%)
Customer_Segment: 0 missing (0.0%)
Order_Date: 0 missing (0.0%)
Order_Time: 0 missing (0.0%)
Sales_Channel: 0 missing (0.0%)
Store_ID: 0 missing (0.0%)
Store_Name: 0 missing (0.0%)
Country: 0 missing (0.0%)
Region: 0 missing (0.0%)
City: 0 missing (0.0%)
Product_ID: 0 missing (0.0%)
Product_Name: 144 missing (0.798%)
Product_Category: 0 missing (0.0%)
Product_Subcategory: 0 missing (0.0%)
Quantity: 0 missing (0.0%)
Unit_Price: 0 missing (0.0%)
Discount_Percentage: 0 missing (0.0%)
Sales_Amount: 0 missing (0.0%)
Cost_Amount: 0 missing (0.0%)
Profit: 0 missing (0.0%)
Payment_Method: 147 missing (0.815%)
Order_Status: 0 missing (0.0%)
Shipping_Method: 0 missing (0.0%)
Delivery_Days: 162 missing (0.898%)
Return_Flag: 0 missing (0.0%)
Return_Reason: 16168 missing (89.598%)
Sales_Representative: 0 missing (0.0%)
Promotion_Code: 9737 missing (53.96%)
Customer_Rating: 3435 missing (19.036%)
Inventory_Level: 198 missing (1.097%)
Order_Year: 0 missing (0.0%)

In [45]:
for column in df.columns:
    uniqueList = list(df[column].unique())
    uniqueLen = len(uniqueList)
    print(f"{column}: {uniqueLen} elements")
    print(uniqueList[:min(10, uniqueLen)]) #Prints the first ten values

Transaction_ID: 18000 elements
['T02016694', 'T02016374', 'T02004099', 'T02010280', 'T02012685', 'T02003704', 'T02016542', 'T02013460', 'T02001029', 'T02001635']
Order_ID: 14541 elements
['O0116694', 'O0108187', 'O0104099', 'O0110280', 'O0112685', 'O0101852', 'O0116542', 'O0113460', 'O0101029', 'O0101635']
Customer_ID: 4882 elements
['C01482', 'C01591', 'C04140', 'C03663', 'C02749', 'C00959', 'C02232', 'C00719', 'C01511', 'C04415']
Customer_Name: 1180 elements
['Sophia Smith', 'Hannah King', 'Emma Wilson', 'Daniel Clark', 'Mia Miller', 'Evelyn Adams', 'Olivia Walker', 'Emily Moore', 'Freya Williams', 'Lily Allen']
Customer_Age: 61 elements
[np.float64(28.0), np.float64(46.0), np.float64(42.0), np.float64(18.0), np.float64(37.0), np.float64(44.0), np.float64(54.0), np.float64(49.0), np.float64(22.0), np.float64(48.0)]
Customer_Gender: 7 elements
['Male', 'Female', 'Non-binary', 'male', 'FEMALE', nan, 'Non Binary']
Customer_Segment: 6 elements
['Consumer', 'Corporate', 'Returning Customer', 'New Customer', 'Small Business', 'Premium']
Order_Date: 1461 elements
['2022-10-06', '2024-06-03', '2024-12-19', '2025-10-05', '2022-09-13', '2023-03-27', '2022-07-25', '2024-02-20', '2024-12-25', '2022-01-18']
Order_Time: 15201 elements
['11:30:55', '17:06:29', '08:22:11', '14:32:43', '14:55:16', '10:40:05', '14:32:42', '03:57:57', '11:38:30', '08:37:21']
Sales_Channel: 4 elements
['Online', 'B2B Portal', 'Retail Store', 'Phone Order']
Store_ID: 12 elements
['LA-01', 'SYD-01', 'PAR-01', 'NYC-01', 'CHI-01', 'TOR-01', 'VAN-01', 'AUS-01', 'LON-01', 'COL-01']
Store_Name: 12 elements
['Los Angeles Downtown', 'Sydney CBD', 'Paris Central', 'New York Central', 'Chicago Loop', 'Toronto Central', 'Vancouver West', 'Austin Business', 'London City', 'Cologne Business']
Country: 6 elements
['United States', 'Australia', 'France', 'Canada', 'United Kingdom', 'Germany']
Region: 14 elements
['West', 'New South Wales', 'Île-de-France', 'Northeast', 'Midwest', 'Ontario', 'British Columbia', 'South', 'England', 'North Rhine-Westphalia']
City: 15 elements
['LOS ANGELES', 'Sydney', 'Paris', 'New York', 'Chicago', 'Toronto', 'Vancouver', 'Austin', 'London', 'Cologne']
Product_ID: 28 elements
['P026', 'P005', 'P017', 'P008', 'P013', 'P012', 'P027', 'P003', 'P006', 'P002']
Product_Name: 29 elements
['Webcam HD', 'Office Keyboard', 'Copy Paper Box', 'SmartDock USB-C', 'Desk Lamp', 'Ergo Footrest', 'Security Camera', 'EdgeTab 11 Tablet', 'Precision Mouse', 'ProBook 16 Laptop']
Product_Category: 7 elements
['Electronics', 'Office Supplies', 'Furniture', 'Appliances', 'FURNITURE', 'electronics', 'Office supplies']
Product_Subcategory: 17 elements
['Cameras', 'Accessories', 'Paper', 'Lighting', 'Office Furniture', 'Tablets', 'Laptops', 'Climate', 'Monitors', 'Storage']
Quantity: 15 elements
[np.int64(2), np.int64(6), np.int64(11), np.int64(4), np.int64(1), np.int64(3), np.int64(5), np.int64(8), np.int64(7), np.int64(9)]
Unit_Price: 12445 elements
[np.float64(85.29), np.float64(58.85), np.float64(43.92), np.float64(115.34), np.float64(69.71), np.float64(79.96), np.float64(41.63), np.float64(159.81), np.float64(503.31), np.float64(39.72)]
Discount_Percentage: 10 elements
[np.float64(5.0), np.float64(15.0), np.float64(0.0), np.float64(20.0), np.float64(10.0), np.float64(25.0), np.float64(30.0), np.float64(45.0), np.float64(60.0), np.float64(110.0)]
Sales_Amount: 15083 elements
[np.float64(162.05), np.float64(300.13), np.float64(74.66), np.float64(1078.46), np.float64(237.03), np.float64(75.96), np.float64(118.64), np.float64(159.81), np.float64(956.28), np.float64(168.81)]
Cost_Amount: 14213 elements
[np.float64(115.61), np.float64(237.0), np.float64(73.17), np.float64(897.91), np.float64(164.95), np.float64(50.09), np.float64(102.11), np.float64(118.34), np.float64(805.86), np.float64(124.22)]
Profit: 10667 elements
[np.float64(46.44), np.float64(63.13), np.float64(1.49), np.float64(180.55), np.float64(72.08), np.float64(25.87), np.float64(16.53), np.float64(41.47), np.float64(150.42), np.float64(44.59)]
Payment_Method: 11 elements
['Credit Card', 'Debit Card', 'paypal', 'Apple Pay', 'Cash', 'PayPal', 'Bank Transfer', 'credit card', 'Bank transfer', nan]
Order_Status: 8 elements
['Completed', 'Shipped', 'Returned', 'Processing', 'Cancelled', 'SHIPPED', 'completed', 'processing']
Shipping_Method: 4 elements
['Standard', 'Next Day', 'Express', 'Pickup']
Delivery_Days: 12 elements
[np.float64(4.0), np.float64(6.0), np.float64(2.0), np.float64(0.0), np.float64(7.0), np.float64(1.0), np.float64(3.0), np.float64(5.0), np.float64(9.0), np.float64(nan)]
Return_Flag: 2 elements
['No', 'Yes']
Return_Reason: 7 elements
[nan, 'Damaged', 'Changed Mind', 'Other', 'Defective', 'Late Delivery', 'Wrong Item']
Sales_Representative: 16 elements
['James Anderson', 'Ella Lewis', 'Liam Davis', 'Grace Harris', 'Sophia Brown', 'Noah Wilson', 'Olivia Martin', 'David Walker', 'Mia Taylor', 'Amelia Jackson']
Promotion_Code: 11 elements
['SAVE10', nan, 'HOLIDAY20', 'BLACKFRIDAY25', 'MOM15', 'HALLOWEEN15', 'BACK2WORK', 'VALENTINE20', 'SUMMER10', 'CORP5']
Customer_Rating: 6 elements
[np.float64(4.0), np.float64(5.0), np.float64(nan), np.float64(2.0), np.float64(1.0), np.float64(3.0)]
Inventory_Level: 149 elements
[np.float64(81.0), np.float64(123.0), np.float64(93.0), np.float64(59.0), np.float64(56.0), np.float64(35.0), np.float64(67.0), np.float64(57.0), np.float64(nan), np.float64(48.0)]
Order_Year: 4 elements
[np.int64(2022), np.int64(2024), np.int64(2025), np.int64(2023)]